### ISSUE TITLE
[feature_request]: support exporting whole website into single pdf file

### ISSUE THREAD

**Issue by dwancn** [jgazeau/website2pdf#107]
### What is missing in the project?

Each page is now exported into a separate pdf file. Shall we add an option to export the whole website into a single pdf file?

**Comment by jgazeau** [comment]
Hi @dwancn , Indeed that could be an option to add.
One library that could be used is [pdf-merger-js](https://www.npmjs.com/package/pdf-merger-js). I'll check that ASAIC.

**Comment by jgazeau** [comment]
Hi @dwancn , the feature is now available in the 0.0.14 of website2pdf. Don't hesitate to try it out.

**Comment by dawanmt** [comment]
> Hi @dwancn , the feature is now available in the 0.0.14 of website2pdf. Don't hesitate to try it out.

Great thanks for your support! @jgazeau
