### ISSUE TITLE
[feature_request]: merge all pdfs in sitemap urls' order

### ISSUE THREAD

**Issue by dwancn** [jgazeau/website2pdf#117]
### What is missing in the project?

Currently pdf files could be merged into single one with random order. Shall we merge all pdf files in sitemap urls' order? I have a patch locally for pull request if push permission is granted.

**Comment by jgazeau** [comment]
Hi @dwancn , you can push a PR on this repo based on your forked repo and branch. Ill have a look at it.

**Comment by jgazeau** [comment]
Close by #120
