### ISSUE TITLE
[feature_request]: name of generated PDF should be exactly same as being set in title without any manipulation

### ISSUE THREAD

**Issue by pankajgupta1206** [jgazeau/website2pdf#45]
### What is missing in the project?

Name of generated PDF should be exactly same as being set in title without any manipulation . Currently spaces , dot and hyphen in title are being replaced by underscore in generated PDF name . We have requirement to keep to it as it as it is being set in title .

**Comment by jgazeau** [comment]
I agree, actually I don't remember exactly why I had put this behavior. but it would make more sense to keep the responsibility on user side and that no changes should be made by the lib.

**Comment by jgazeau** [comment]
@pankajgupta1206 feature released as part of the 0.0.8.

**Comment by pankajgupta1206** [comment]
Thanks Jordan for the help.
