### ISSUE TITLE
[feature_request]: Support for multi page pdfs

### ISSUE THREAD

**Issue by distbit0** [jgazeau/website2pdf#59]
### What is missing in the project?

It seems that at the moment the resulting pdf for each page is limited to one page in length. When I try to create pdfs for such webpages which exceed 1 page worth of content, they are unceremoniously cropped at the bottom, often half way through a line of text.

### Solution?

Could you please add support for web pages which are longer than a single page. This would be extremely useful. Thx

**Comment by jgazeau** [comment]
Hi @distbit0 ,
Actually the library is able to generate multi pages pdfs.
What you can do is to check the print preview in a chromium based browser of the page you are trying to print.
It should be the same result as in the pdf generated.
* If yes, I thing that you have to check the page you are trying to print. If it is on your own website, maybe you can add some css media rules to put a specific page break.
```
@media print
    break-after: page
```
* If not can you provide a reproducer so I can help you?

**Comment by distbit0** [comment]
Oh haha yeah I think I might have just not scrolled down or something. Now that I check again, I realise that website2pdf actually was exporting multi page websites properly... nvm
