### ISSUE TITLE
[feature]: option to save file by last url fragment

### ISSUE THREAD

**Issue by distbit0** [jgazeau/website2pdf#77]
### Steps that lead to the issue

I have a set of urls I would like to convert into pdfs and so have created a sitemap.xml file containing all said urls. When I run website2pdf only a few of them are downloaded, despite the results summary stating that all are "printed".

The sitemap.xml I used is attached (I hosted it at localhost using a flask server). 
[sitemap.zip](https://github.com/jgazeau/website2pdf/files/10474104/sitemap.zip)

The output from running website2pdf was the following: 
![image](https://user-images.githubusercontent.com/10890247/213909562-ed31619e-40ba-4764-9cfb-d932c6310ff9.png)

However the resulting folder structure which it created looks very different and contains significantly fewer documents: 
![image](https://user-images.githubusercontent.com/10890247/213909587-c3e1feb2-8bde-401f-a5ea-509eff99b543.png)

I am using v0.0.8

When I run the command, it is much faster than I would have expected it to be based on how long it has taken to download a similar # of urls to the number of urls in the sitemap file, which leads me to suspect that it completely skipped even attempting to download most of the urls in the provided sitemap file.

### Expected behavior

All urls in sitemap.xml to be downloaded and saved.

### Reproducer

- host above attached sitemap.xml at localhost on port 8972
- run npx website2pdf --sitemapUrl  http://localhost:8972/sitemap.xml

**Comment by jgazeau** [comment]
Hi @distbit0 ,

After checking your example, the issue is that all **Curie-Docs-for-Partners.*** pages have the same title. That's why when website2pdf is trying to save them, they are all overriden except the last one.

To solve that you can change the title tag of your pages to a less generic one.

On my side I will add a new feature to save pdf files based on the name of the url wether than the title (by default files will still be saved by title)
Kr,

**Comment by jgazeau** [comment]
Hi @distbit0 , I've created a 0.0.11 to help you. Also just to mention, I have added a **serve-sitemap** option to directly serve a single sitemap file during the process. You won't need to serve it locally using your own http server.
Regards,

**Comment by distbit0** [comment]
Thank you so much! That is awesome :) @jgazeau

**Comment by distbit0** [comment]
That definitely solved the original problem, although now I have noticed that about half of the notion pages are not fully loading before being captured, resulting in about half of the pdfs containing loading symbols rather than the content of the page.. Here is the updates sitemap.xml file which I am using btw. [sitemap.zip](https://github.com/jgazeau/website2pdf/files/10540886/sitemap.zip)

**Comment by jgazeau** [comment]
@distbit0 indeed didnt have the issue before but I'll definitively have a look at that. I've inquire this [issue](https://github.com/jgazeau/website2pdf/issues/82) to track it. I'll have a look as soon as I can.

**Comment by distbit0** [comment]
Thanks so much @jgazeau :)
